// Generated with Shader Minifier 1.6.0 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef SHADER_H_
# define SHADER_H_
# define VAR_t "v"

const char *shader_frag =
 "#version 130\n"
 "uniform float v;"
 "const vec2 f=vec2(1920,1080);"
 "float m(float v)"
 "{"
   "return fract(sin(v)*265871.1723);"
 "}"
 "float m(vec2 v)"
 "{"
   "return m(dot(v,vec2(11,313)));"
 "}"
 "float x(vec2 v)"
 "{"
   "vec2 y=floor(v);"
   "v-=y;"
   "return mix(mix(m(y),m(y+vec2(1,0)),v.x),mix(m(y+vec2(0,1)),m(y+vec2(1)),v.x),v.y);"
 "}"
 "float s(vec2 v)"
 "{"
   "return x(v)*.5+x(v*2.1)*.25+x(v*3.9)*.125;"
 "}"
 "vec2 n(vec2 v)"
 "{"
   "vec2 y=vec2(4);"
   "return floor(v*y)/y;"
 "}"
 "vec2 m(vec2 v,vec2 y)"
 "{"
   "return mod(v,y)-y*.5;"
 "}"
 "float m(vec3 v)"
 "{"
   "return max(max(v.x,v.y),v.z);"
 "}"
 "float p(vec2 v)"
 "{"
   "return max(v.x,v.y);"
 "}\n"
 "#define RM(a)mat2(cos(a),sin(a),-sin(a),cos(a))\n"
 "vec2 i=vec2(0);"
 "float a=0.,r=0.,c=0.,e=0.;"
 "vec3 z,y;"
 "float n(vec3 v)"
 "{"
   "float y=1e6;"
   "e=0.;"
   "float f=s((v.xz-i)*.1),z=v.y+8.-(f-.3)*18.*r;"
   "if(y>z)"
     "y=z,e=1.;"
   "z=-m(abs(v)-vec3(20,8,30));"
   "if(y>z)"
     "y=z,e=0.;"
   "if(a!=0.)"
     "{"
       "vec3 a=vec3(m(v.xz-i,vec2(12,25)),v.y-f*8.+6.).xzy;"
       "float z=length(a)-3.;"
       "if(y>z)"
         "y=z,e=2.;"
     "}"
   "if(c>0.)"
     "y=min(y,m(dot(.01*vec3(v.xz-floor(i),v.y).xzy,vec3(3.2,57.55,117.234)))*20.1-.01);"
   "return y;"
 "}"
 "float m(vec3 v,vec3 f)"
 "{"
   "vec3 i=1./f,m=sign(f),e=z=floor(v),a=(e-v+.5+m*.5)*i;"
   "f=vec3(0);"
   "for(float r=0.;r<128.;r++)"
     "{"
       "float c=n(e+.5);"
       "if(c<0.)"
         "return y=-f*m,a=(e-v+.5-m*.5)*i,max(max(a.x,a.y),a.z);"
       "z=e;"
       "f=step(a.xyz,a.yzx)*step(a.xyz,a.zxy);"
       "a+=f*m*i;"
       "e+=f*m;"
     "}"
   "return 1e6;"
 "}"
 "mat3 m(vec3 v,vec3 y,vec3 m)"
 "{"
   "v=normalize(v-y);"
   "y=normalize(cross(m,v));"
   "m=normalize(cross(v,y));"
   "return mat3(y,m,v);"
 "}"
 "vec3 n(vec3 v,vec3 y)"
 "{"
   "float m=step(s(-i*.041+v.xz*(8./v.y)*.1),.3);"
   "return mix(mix(vec3(.1,.3,.7),2.*vec3(.9,.6,.4),pow(max(dot(v,y)*1.1,0.),20.)),vec3(1),m);"
 "}"
 "void main()"
 "{"
   "vec2 s=gl_FragCoord.xy/f.xy-.5;"
   "s.x*=f.x/f.y;"
   "float x,d=0.,C=2.,F=0.,g=0.;"
   "vec2 R=vec2(.2);"
   "vec3 l=vec3(0,0,28),G=vec3(0,0,-30);"
   "float E=0.,D=(v<1376.?"
     "v:"
     "v+32.)/128.,B=fract(D),A=floor(D);"
   "D=smoothstep(0.,.125,B)*smoothstep(1.,.75,B);"
   "if(A<1.)"
     "l=vec3(0,4,-25.+B*30.),G=vec3(0,0,-30);"
   "else if(A<2.)"
     "l=vec3(10,4,-25.+B*30.),G=vec3(-10,0,l.z);"
   "else if(A<3.)"
     "l=vec3(8,4,B*10.),G=vec3(0,0,-30);"
   "else if(A<4.)"
     "l=vec3(0,2,20.+B*8.),G=vec3(0,0,-30);"
   "else if(A<5.)"
     "C=1.-floor(B*4.)/4.;"
   "if(A>4.)"
     "{"
       "C=0.;"
       "d=1.;"
       "g=1.;"
       "vec2 v=(vec2(m(A),m(A+.1))-.5)*vec2(20,4);"
       "G=mix(vec3(-20,-4,-30),vec3(20,0,30),vec3(m(A+.1),m(A+.2),m(A)));"
       "l=vec3(v.x,v.y+2.,30.-B*40.);"
     "}"
   "if(A>6.)"
     "l=vec3(-8.+16.*mod(A-7.,2.),2,-20.+B*40.),G=vec3(0,-8,-3),F=1.;"
   "if(A>8.)"
     "l=vec3(-8.+16.*mod(A-7.,2.),7,(-20.+B*40.)*(A>9.?"
       "-1.:"
       "1.)),G=vec3(0,-8,1)+l;"
   "if(A>10.)"
     "R=vec2(0,2),E=.4*(mix(m(A),m(A+3.),B)-.5),l=vec3(0,2,30.-B*16.)+mix(vec3(sin(A*17.)*10.,2.+2.*cos(A*4.),0),vec3(sin(A*11.)*10.,2.+2.*cos(A*14.),0),B),G=vec3(0,0,-30);"
   "i=R*smoothstep(640.,704.,v)*(v-640.);"
   "r=smoothstep(256.,768.,v);"
   "if(A>10.)"
     "a=1.;"
   "if(A>12.)"
     "c=1.;"
   "D*=smoothstep(1880.,18e2,v);"
   "B=0;"
   "vec3 H=vec3(0);"
   "for(float A=0.;A<4.;++A)"
     "{"
       "x=fract(v+m(A)+m(s.x)+m(s.y));"
       "vec2 a=s+(vec2(m(x+s.x),m(x+s.y))-.5)/f;"
       "x=fract(m(a.x)+m(a.y)+A);"
       "vec3 i=l;"
       "mat3 R=m(l,G,vec3(sin(E),1,0));"
       "vec3 r=R*normalize(vec3(a,-1)),D=vec3(1);"
       "for(float A=0.;A<3.;++A)"
         "{"
           "float f=m(i,r);"
           "if(A==0.)"
             "B=f;"
           "vec3 a=i+r*f,s=z,l=fract(a);"
           "vec2 G=abs(l.xz*y.y+l.xy*y.z+l.yz*y.x),c=abs(s.xz*y.y+s.xy*y.z+s.yz*y.x);"
           "l=vec3(0);"
           "vec3 R=vec3(.7);"
           "f=.6;"
           "if(g>0.&&e==1.)"
             "R=vec3(.3,.8,.4)*(.6+.4*m(c+n(G))),f=.9;"
           "else if(e==0.)"
             "{"
               "if(y.y<0.||d>0.&&s.y>0.)"
                 "{"
                   "if(d>0.)"
                     "l+=n(normalize(s),normalize(vec3(vec2(1,-1)+vec2(-2,2)*((v-1e3)/5e2),1).xzy));"
                   "if(C>0.)"
                     "{"
                       "vec3 v=vec3(1.5)*step(p(abs(m(s.xz,vec2(10)))-vec2(1)),1.)*step(s.z,C*40.-30.);"
                       "l+=v;"
                     "}"
                 "}"
               "else if(y.y==0.)"
                 "f=.4;"
             "}"
           "else if(e==2.)"
             "R=vec3(.3,.7,.4)*(.6+.4*m(c+n(G))),f=.2;"
           "if(F>0.&&y.y>0.&&s.y<=-8.)"
             "R=vec3(1),f=.05;"
           "s=D*l;"
           "if(!any(isnan(s)))"
             "H+=s;"
           "D*=R;"
           "i=a+.01*y;"
           "r=normalize(mix(reflect(r,y),vec3(m(x+=a.z),m(x+=r.x),m(x+=a.y))-.5,f));"
           "r*=sign(dot(r,y));"
         "}"
     "}"
   "H=H/4.*D;"
   "gl_FragColor=vec4(pow(H,vec3(1./2.2)),B);"
 "}";

#endif // SHADER_H_
